Initial workflow implementation
geoadmin/tool-github-workflows pull request #1
Opened 2021-10-27 14:57 UTC by ltshb

2021-11-01 15:01 UTC, boecklic requested changes

2021-11-01 15:01 UTC, boecklic commented on .github/release-drafter-labeler-config.yml
> +      - '/breaking-changes-.+/'
I would remove this. Wheather a change is braking or not is imho a question of communication and should be tackled there. It's not sufficient to just name a branch 'braking-asdf' and then forget about it. We need a strategy for communicating braking changes. Release notes are the wrong place since it's too late.

2021-11-01 15:21 UTC, ltshb commented on .github/release-drafter-labeler-config.yml
> +      - '/breaking-changes-.+/'
Done.

2021-11-01 15:39 UTC, boecklic approved these changes

2021-11-01 15:41 UTC, merged

2021-11-01 17:18 UTC, davidoesch commented on .github/release-drafter-labeler-config.yml
> +      - '/breaking-changes-.+/'
do not agree: I would keep the label "breaking".  because this actual release breaks it. Of  course  it has to be communicated in advance. But it helps to understand  why since a specific release/dates sth does not work. we did that in the past several times when removing data layers (first announce, then actually note that with this release see eg http://api.geo.admin.ch/releasenotes/index.html#release-20210630-wednesday-june-30th-2021 )


my 2 cents from the sales department

2021-11-02 04:56 UTC, hansmannj reviewed
Nice, thanks :+1: